"""add deleted and active data to users table

Revision ID: 5500e38686c0
Revises: fbfb815b5dad
Create Date: 2022-05-19 01:37:21.668250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5500e38686c0'
down_revision = 'fbfb815b5dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(create_constraint=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
